name: tdmpc-m2
channels:
  - conda-forge   # Indispensable pour les paquets Mac ARM64 récents
  - pytorch
dependencies:
  - python=3.10   
  - pytorch       
  - torchvision
  - pip
  - pip:
    - termcolor
    - omegaconf
    - pandas
    - wandb
    - moviepy
    - imageio
    # Gym est un cas particulier (voir explication plus bas)
    - gym==0.21.0 
    # Correction pour installer gym 0.21 sur des python récents
    - setuptools==65.5.0 
    - wheel
